name: Publish Package to PyPI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.8
        with:
          pypi_token: ${{ secrets.pypi_api_token }}
